### ISSUE TITLE
Possible bug in with Keypad 2334_222 6 button map

### ISSUE THREAD

**Issue by wonderslug** [nugget/python-insteonplm#111]
Looks like the current mapping for the 6 button mode on the 2334_222 is

`{3: 'C', 4: 'D', 5: 'E', 6: 'F', 7: 'G'}`

But the naming convention is like in the owners manual PDF

![Button Layout](http://wonderslug.s3-website-us-east-1.amazonaws.com/snaps/Keypad_Dimmer_Manual_2334-2xx_Series_2018-10-10_10-19-44.png)

I am wondering if it should be the following on the button mapping for 6?

`{3: 'A', 4: 'B', 5: 'C', 6: 'D'}`

It also showing a group id 7 map, does that do anything on a 2334_222 in 6 mode?

**Comment by wonderslug** [comment]
Sure I was just wondering if the group id of 7 on the 2334_222 when it was in a 6 button configuration did something specific since it was listed in the dict of button labels.

**Comment by teharris1** [comment]
Closing due to PR being merged. Will be released in 0.15.0.
