### ISSUE TITLE
IO Linc Sensor and Open/Closed sensors behave differently

### ISSUE THREAD

**Issue by teharris1** [nugget/python-insteonplm#117]
The IOLinc 2450 sensor is an Open/Closed sensor but it behaves different than the Open/Closed Sensor 2421 and 2843-222 devices. This is confusing to developers and should be corrected. This was temporarily corrected in release 0.15.2 but needs a permanent solution.

**Comment by reisfni** [comment]
I noticed recently that all my 2843-222 sensors in HA (I’m on 0.88.3) show as open when the door is actually closed and vice versa.  Wondering if this bug is to blame or if it’s something else?

**Comment by teharris1** [comment]
Yes, this broke in 0.83.0 but a fix has been submitted to fix it. I am not sure if this will be in 0.83.4 or 0.84.0.
