### ISSUE TITLE
insteonplm_interactive add_all_link sleep not awaited

### ISSUE THREAD

**Issue by garbled1** [nugget/python-insteonplm#212]
insteonplm: add_all_link 0 1 319d11
insteonplm: Starting the All-Linking process
Attempting to link the PLM to device 319d11. 
/opt/homeassistant/lib/python3.7/site-packages/insteonplm/tools.py:145: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(.5, loop=self.loop)

**Comment by teharris1** [comment]
Thanks. This will be fixed in the next release.

**Comment by teharris1** [comment]
This has been fixed and will hit the next release. Thanks for pointing it out.
