### ISSUE TITLE
Auto Discovery

### ISSUE THREAD

**Issue by teharris1** [nugget/python-insteonplm#28]
The ALL-Link response record 0x57 does not consistently return the cat, subcat or firmware information. According to the developers guide this is device dependent. I have seven different device types and only one (motion sensor) returns the cat, subcat and firmware versions.

A command was added in 2007 code 0x50 cmd1 0x03 cmd2 0x00 which will return the product data, however this only works on 1 of my seven devices.  The command that produces the most consistent result is code 0x50 cmd1 0x10 cmd2 0x00.  This works on five of my seven devices. The ones it does not work on are both battery operated so it is possible it works on them as well but that they do not respond to requests until they wake. I have not been able to test this sufficiently yet.

**Comment by lanrongwen** [comment]
Battery Operated devices are only readable when they send data to preserve battery.  From all my digging it looks like tools like the insteon app cache the last state (hence the unknown until first triggered).  When using HouseLink it can't do anything until the device checks in.  It does look like it may have a small windows during checkin to send a command though as it does some syncing at that time in the Houselink software.
