### ISSUE TITLE
I am not famirial with python env.Ubuntu 16

### ISSUE THREAD

**Issue by zirexix** [nugget/python-insteonplm#75]
marius@HPP:~/CPP/python-insteonplm$ pip install .
Processing /home/marius/CPP/python-insteonplm
Collecting pyserial==3.2.0 (from insteonplm==0.9.1)
  Using cached https://files.pythonhosted.org/packages/2c/c2/2a391a69730c05a646f27e71e965cf8a0e9ccd72c0f0b870b74d47f3c32b/pyserial-3.2-py2.py3-none-any.whl
Collecting pyserial-asyncio (from insteonplm==0.9.1)
  Using cached https://files.pythonhosted.org/packages/d5/5e/518ace81b212db9a6458bf86ae9626c850bdc06ab133edd11f9b2a29ec47/pyserial_asyncio-0.4-py3-none-any.whl
Collecting async_timeout (from insteonplm==0.9.1)
  Using cached https://files.pythonhosted.org/packages/1d/b9/213521db2918b5b7f7df333a33ea3d38ba70ba705d9db6c29f0343c213ea/async_timeout-2.0.1-py3-none-any.whl
Building wheels for collected packages: insteonplm
  Running setup.py bdist_wheel for insteonplm ... done
  Stored in directory: /home/marius/.cache/pip/wheels/6d/be/e2/64b09e0f501d6f92ca9f304326f0360f8e504febaf1e0233fc
Successfully built insteonplm
Installing collected packages: pyserial, pyserial-asyncio, async-timeout, insteonplm
  Found existing installation: pyserial 3.0.1
Cannot uninstall 'pyserial'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
marius@HPP:~/CPP/python-insteonplm$

**Comment by teharris1** [comment]
Did you need help with something?
