### ISSUE TITLE
I/O Linc relay (switch side) not appearing.

### ISSUE THREAD

**Issue by majortom64** [nugget/python-insteonplm#85]
I have an I/O Linc used for a garage door opener. The sensor side appears, and I thought that in previous versions, if I clicked on the circle in the interface, it would toggle the relay (although I maybe mistaken about that). The relay side does not appear anywhere I can find in HASS, so while I can see the state sensor, I cannot control the relay.

Not sure what is wrong.

**Comment by teharris1** [comment]
I just installed one of them myself and had the same issue. The issue has been fixed in HA abs should be in the next release.
________________________________

**Comment by teharris1** [comment]
This is working for me now. Can I close it out?

**Comment by majortom64** [comment]
Works for me again. Thanks!
